### PR TITLE
added a resource id route formatter

### PR DESCRIPTION
**Pull request by BartWillems**
Signed-off-by: Bart Willems <bwillems@protonmail.com>

### CODE REVIEW

**Comment by jtescher** [comment]
@BartWillems this looks reasonable. Seems like wanting to customize the formatter beyond what is currently provided will be common, what do you think about #21 as an alternative? Basically allow the regex and the replacement value to be customized, avoiding the need to enumerate all the formats.

**Comment by BartWillems** [comment]
@jtescher #21 looks like a better solution. Would you be interested in also adding the resource id regex to the library?

**Comment by jtescher** [comment]
@BartWillems I initially was trying to do that, but the regular expressions can't be constants so currently it is just exposing the string version of the uuid regex because it is fairly complex and not easy to verify yourself. Didn't seem as useful to expose "\d+" as a const as you still have to manually construct a `RegexFormatter` either way and people may have many different tweaks to what they allow as their resource id besides just digits.

E.g. `RegexFormatter::new(DIGITS_REGEX, "id")` vs `RegexFormatter::new(r"\d+", "id")` are pretty similar, and if you prefer the first you can always pull out to a const in your app?

**Comment by BartWillems** [comment]
@jtescher Yeah fair enough, I will close this PR then in favor of #21. 

Also a quick note, `r"\d+"` wouldn't always work because paths like `/api/v3/some/path` would also get normalized.

**Pull request closed without merging**
